### ISSUE TITLE
Unable to remove all custom positions to show only the medals and unable to set a custom position above 10k

### ISSUE THREAD

**Issue by XenoJiiva0053** [Banalian/ExtraLeaderboardPositions#29] opened 2024-06-24 12:49 UTC
**Describe the bug**
Cant remove all custom positions to show only the medals and cant put a position over 10k in custom

**Expected behavior**
being able to set a position above 10k and remove all custom positions to only show the medals

**Comment by Banalian** [comment] 2024-07-08 01:01
About the 10k part, this is intended behavior. I can't use the top endpoint with a number above 10k, this was unintended behavior, so you won't be able to select a position above 10k sadly. I could however add the change to allow 0 custom positions!

**Comment by XenoJiiva0053** [comment] 2024-07-08 01:08
Just wondering how is it able to display my position accurately above 10k but not a custom 1?

**Comment by Banalian** [comment] 2024-07-08 01:14
because the medals and pb uses a different endpoint that returns more accurate results above 10k, but the custom positions uses an endpoint that initially also had that upgraded precise position (was 10k, but then upgraded to 100k max), but they reverted that decision since it was unintended behavior for that endpoint. Since I have no other choices but to use that endpoint for the custom positions, I can't allow custom positions above 10k sadly.

**Comment by XenoJiiva0053** [comment] 2024-07-08 01:23
Ah 8k

**Comment by Banalian** [comment] 2024-07-10 01:48
This was done with #33 , will be in 1.4.0! Thanks for the suggestion

**Closed by Banalian** 2024-07-10 01:48 UTC
Labels: bug
